/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wahaha2019.exercise;

import org.junit.jupiter.api.Test;

import static com.github.wahaha2019.exercise.ArrayList.newIntSerial;
import static org.junit.jupiter.api.Assertions.*;

public class ArrayListTest {

  @Test
  public void create() {
    int capacity = 256;
    ArrayList aist = new ArrayList(capacity);
    assertTrue(aist.isEmpty());
    assertEquals(aist.getSize(), 0);
    assertEquals(aist.getCapacity(), capacity);
    int size = 128;
    aist.setSize(size);
    assertFalse(aist.isEmpty());
    assertEquals(aist.getSize(), size);
    assertEquals(aist.getCapacity(), capacity);
    size = 4096;
    aist.setSize(size);
    assertTrue(aist.isFull());
    assertFalse(aist.isEmpty());
    assertEquals(aist.getSize(), size);
    assertEquals(aist.getCapacity(), size);
  }

  @Test
  public void clear() {
    int capacity = 256;
    ArrayList aist = new ArrayList(capacity);
    int size = 128;
    aist.setSize(size);
    aist.clear();
    assertTrue(aist.isEmpty());
    assertEquals(aist.getSize(), 0);
    assertEquals(aist.getCapacity(), capacity);
  }

  @Test
  public void get() {
    int capacity = 256;
    ArrayList aist = new ArrayList(capacity);
    assertThrows(IndexOutOfBoundsException.class, () -> {
      Object ele = aist.get(0);
    });
  }

  @Test
  public void set() {
    int capacity = 256;
    ArrayList<String> aist = new ArrayList<>(capacity);
    assertThrows(IndexOutOfBoundsException.class, () -> {
      aist.set(0, "0");
    });
    aist.setSize(1);
    aist.set(0, "0");
    assertEquals(aist.get(0), "0");
    aist.setSize(2);
    assertNull(aist.get(1));
    aist.set(1, "1");
    assertEquals(aist.get(1), "1");
  }

  @Test
  public void insert() {
    int capacity = 3;
    ArrayList<String> aist = new ArrayList<>(capacity);
    aist.insert(0, "0");
    assertEquals(aist.get(0), "0");
    assertEquals(aist.getSize(), 1);
    aist.setSize(1);
    aist.set(0, "1");
    aist.insert(0, "0");
    assertEquals(aist.get(0), "0");
    assertEquals(aist.get(1), "1");
    assertEquals(aist.getSize(), 2);
    aist.insert(1, "b");
    assertEquals(aist.get(0), "0");
    assertEquals(aist.get(1), "b");
    assertEquals(aist.get(2), "1");
    assertEquals(aist.getSize(), 3);
    aist.insert(2, "B");
    assertEquals(aist.get(0), "0");
    assertEquals(aist.get(1), "b");
    assertEquals(aist.get(2), "B");
    assertEquals(aist.get(3), "1");
    assertEquals(aist.getSize(), 4);
    ArrayList aist2 = newIntSerial(10);
    ArrayList<Integer> aist3 = new ArrayList<Integer>(10);
    aist3.append(9);
    for (int i = 8; i >= 0; i--) {
      aist3.insert(0, i);
    }
    assertEquals(aist3, aist2);
    assertEquals(aist3.hashCode(), aist2.hashCode());
  }

  @Test
  public void delete() {
    ArrayList aist = newIntSerial(3);
    aist.delete(0);
    assertEquals(aist.get(0), 1);
    assertEquals(aist.get(1), 2);
    assertEquals(aist.getSize(), 2);
    aist = newIntSerial(3);
    aist.delete(1);
    assertEquals(aist.get(0), 0);
    assertEquals(aist.get(1), 2);
    assertEquals(aist.getSize(), 2);
    aist = newIntSerial(3);
    aist.delete(2);
    assertEquals(aist.get(0), 0);
    assertEquals(aist.get(1), 1);
    assertEquals(aist.getSize(), 2);
  }

  @Test
  public void append() {
    ArrayList aist = newIntSerial(3);
    aist.append(3);
    assertEquals(aist.get(0), 0);
    assertEquals(aist.get(1), 1);
    assertEquals(aist.get(2), 2);
    assertEquals(aist.get(3), 3);
    assertEquals(aist.getSize(), 4);
  }

  @Test
  public void deleteToTop() {
    ArrayList aist = newIntSerial(3);
    aist.deleteToTop(1);
    assertEquals(aist.get(0), 2);
    assertEquals(aist.getSize(), 1);
    aist = newIntSerial(3);
    aist.deleteToTop(0);
    assertEquals(aist.get(0), 1);
    assertEquals(aist.get(1), 2);
    assertEquals(aist.getSize(), 2);
    aist = newIntSerial(5);
    aist.deleteToTop(2);
    assertEquals(aist.get(0), 3);
    assertEquals(aist.get(1), 4);
    assertEquals(aist.getSize(), 2);
    aist = newIntSerial(5);
    aist.deleteToTop(3);
    assertEquals(aist.get(0), 4);
    assertEquals(aist.getSize(), 1);
    aist = newIntSerial(5);
    aist.deleteToTop(4);
    assertTrue(aist.isEmpty());
  }

  @Test
  public void deleteToEnd() {
    ArrayList aist = newIntSerial(3);
    aist.deleteToEnd(1);
    assertEquals(aist.get(0), 0);
    assertEquals(aist.getSize(), 1);
    aist = newIntSerial(5);
    aist.deleteToEnd(0);
    assertTrue(aist.isEmpty());
  }

  @Test
  public void equals() {
    ArrayList aist1 = newIntSerial(3);
    ArrayList aist2 = newIntSerial(5);
    assertNotEquals(aist1, aist2);
    aist2.setSize(3);
    assertEquals(aist1, aist2);
  }

  @Test
  public void hash() {
    ArrayList aist1 = newIntSerial(3);
    ArrayList aist2 = newIntSerial(5);
    aist2.setSize(3);
    assertEquals(aist1.hashCode(), aist2.hashCode());
  }

  @Test
  public void testToString() {
    assertEquals(new ArrayList().toString(), "ArrayList{size=0,data={}}");
    ArrayList aist1 = newIntSerial(3);
    ArrayList aist2 = newIntSerial(5);
    aist2.setSize(3);
    System.out.println(aist1);
    assertEquals(aist1.toString(), "ArrayList{size=3,data={0,1,2}}");
    assertEquals(aist1.toString(), aist2.toString());
  }

}
